services:
  - type: web
    name: coworkspace-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coworkspace-db
          property: connectionString
databases:
  - name: coworkspace-db
