services:
  - type: web
    name: my-backend
    runtime: docker
    plan: free
    dockerfilePath: src/backend/Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      # PORT impostata da Render, backend legge process.env.PORT

  - type: web
    name: my-frontend
    runtime: docker
    plan: free
    dockerfilePath: src/frontend/Dockerfile
    dockerContext: .

databases:
  - name: mydb
    plan: free
