# STEP 1: Usa un'immagine Nginx ufficiale, ottimizzata per leggerezza
FROM nginx:alpine

# STEP 2: Copia tutti i file dalla tua cartella 'src/frontend'
# alla directory predefinita di Nginx nel container.
# Questo includerà i tuoi file HTML, CSS e JS.
COPY . /usr/share/nginx/html